/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "anxiety": "焦虑",
    "anxiety now, but generate +1 anxiety": " 焦虑现在，但产生 +1 焦虑",
    "Anxiety per second": "焦虑每秒",
    "Buy a house": "买房子",
    "Buy an NFT": "购买 NFT",
    "Costs $1,000.": "费用为 1,000 $。",
    "Costs $200 in collateral. +$200.": "抵押品费用为 200 $。 +200 $。",
    "Costs $50,000 and 4,500 missed opportunities. +$1/s.": "花费 50,000 $和 4,500 次错失机会。 + 1 $/秒。",
    "Costs $550,000. -500 anxiety/s.": "花费 550,000 $。 -500 焦虑/秒。",
    "Costs 10 missed opportunities & must work hard in school. Unlocks the ability to work for money.": "损失 10 次错过的机会，并且必须在学校努力学习。解锁为钱工作的能力。",
    "Costs 3 missed opportunities. Maybe helps with anxiety?": "损失 3 次错失机会。也许有助于缓解焦虑？",
    "Costs 60 missed opportunities and": "损失 60 次错失机会和",
    "Costs 990 anxiety and 5,500 missed opportunities. +$1/s.": "花费 990 次焦虑和 5,500 次错失机会。 + 1 $/秒。",
    "cry": "哭",
    "days old.": " 天了。",
    "doubt": "怀疑",
    "exist": "存在",
    "Existence Simulator": "存在模拟器",
    "Forget hobbies! Study hard for those tests and make something of yourself. (": "忘记爱好！为这些测试努力学习，让自己有所作为。 (",
    "Free! Permanently increases anxiety per second and missed opportunities per second. But by how much? (We never really know, do we?": "自由！每秒永久增加焦虑和每秒错失的机会。但是多少呢？ （我们从来都不知道，不是吗？",
    "Generate money (you have $": "赚钱（你有 $",
    "generating": "生成",
    "Get a good job": "找个好工作",
    "Get a social media account": "获取社交媒体帐户",
    "Go to college": "去上大学",
    "LOADING...": "正在加载...",
    "Look for a job": "找工作",
    "Lose": "失去",
    "missed opportunities": "错失良机",
    "Missed opportunities per second": "每秒错失的机会",
    "Must use BEFORE 18th birthday": "必须在 18 岁生日之前使用",
    "Okay": "好的",
    "only $5.99": "只需 5.99 $",
    "Panic Attack": "惊恐发作",
    "QQ群号": "QQ群号",
    "Start taking naps": "开始小睡",
    "Take an online class": "参加在线课程",
    "Take out a loan": "拿出贷款",
    "Thanks": "谢谢",
    "This game is meant to be played on desktop devices. Sorry.": "该游戏旨在在桌面设备上玩。对不起。",
    "try your best": "尽你所能",
    "Welcome to the Existence Simulator. Begin existing by clicking the 'Exist' button.": "欢迎来到存在模拟器。通过单击“存在”按钮开始存在。",
    "work": "工作",
    "Work hard in school": "在学校努力工作",
    "x": "X",
    "years and": " 年",
    "years old.": "岁。",
    "You are": "你活了 ",
    "You had a nervous breakdown at": "你精神崩溃了，在",
    "You no longer exist.": "你已经不存在了。",
    "As you exist, you generate anxiety. Try generating at least 10.": "当你存在时，你会产生焦虑。 尝试生成至少 10 个。",
    "Crying removes anxiety immediately--and increases the amount of anxiety you passively generate. Try generating 5 anxiety per second by Crying more.": "哭泣会立即消除焦虑——并增加你被动产生的焦虑程度。 尝试通过多哭，达到每秒产生 5 焦虑。",
    "Generating anxiety by just existing takes a lot of effort. To generate anxiety automatically, try Crying.": "仅仅通过存在来产生焦虑需要付出很多努力。 要自动产生焦虑，请尝试哭泣。",
    "Now you're a regular anxiety machine--just like real life! Try making it to 200 anxiety.": "现在你是一个经常焦虑的机器——就像现实生活一样！ 尝试达到 200 焦虑。",
    "The more you exist, the more anxiety you generate. If you max out your anxiety, you'll have a nervous breakdown (game over), so you'll need to use it on something. The 'Doubt' button generates Missed Opportunities that you can exchange for anxiety.": "你存在的越多，你产生的焦虑就越多。 如果你最大限度地消除焦虑，你就会精神崩溃（游戏结束），所以你需要在某些事情上使用它。 “怀疑”按钮会产生错失的机会，您可以用这些机会换取焦虑。",
    "Now you know the mitochondria are the powerhouse of the cell. Your social anxiety is through the roof, but maybe now you can find yourself a job!": "现在你知道线粒体是细胞的动力源。 您的社交焦虑已达到顶峰，但也许现在您可以找到一份工作！",
    "Now you're a regular anxiety machine--just like real life! Try making it to 200 anxiety.": "现在你是一个经常焦虑的机器——就像现实生活一样！ 尝试达到 200 焦虑。",
    "Thanks to all the new skills you've earned, one day you might be able to earn more money at a job you may potentially find in the future when jobs for that skillset are more available!": "多亏了你获得的所有新技能，有一天你可能会在一份工作中赚到更多的钱，当该技能组的工作更多可用时，你可能会找到一份工作！",
    "The only companies hiring right now are the ones paying the bare minimum. But hey -- at least you have your health! (for now!": "目前唯一招聘的公司是支付最低工资的公司。 但是，嘿 - 至少你有你的健康！ （目前！",
    "You're trying to sleep more, which is generating missed opportunities--but its getting harder to fall asleep, so you're generating more anxiety, too.": "你试图睡得更多，这会产生错失的机会——但它越来越难以入睡，所以你也会产生更多的焦虑。",
    "Your social anxiety goes down a bit, but now that you're doomscrolling everyday it's even harder to fall asleep and focus on things that matter (which is what again?": "你的社交焦虑稍微下降了一点，但现在你每天都在做末日卷轴，所以更难入睡并专注于重要的事情（这又是什么？",
    "Now you are really \"enjoying\" what life has to offer. Oh, what beauty it is to be human! Spend your missed opportunties by Trying your Best.": "现在你真的“享受”了生活所提供的一切。 哦，做人是多么美好啊！ 尽最大努力度过错过的机会。",
    "(thanks to your friend's referral code). Maybe you can earn more money?": "（感谢您朋友的推荐代码）。 也许你可以赚更多的钱？",
    "- Automations are": "- 自动化 ",
    "Costs 160 Missed Opportunities and $5000. Propel yourself from the limits of scientific knowledge and take a deep-dive into theoretical computing and software development with a class by Professor Dr. Ambassador Dutchess Kimberly Finebinaryton.": "花费 160 次错过的机会和 $5000。 让自己摆脱科学知识的局限，参加由大使 Dutchess Kimberly Finebinaryton 教授教授的课程，深入了解理论计算和软件开发。",
    "Costs 4,000 Knowledge, 4,000 Influence, and $75,000. Generate +5 Influence per second. Help pass a law that requires colleges to officially recognize idle games as an official sports, and provides funding for team jerseys and computer cafes to practice in.": "花费 4,000 知识、4,000 影响力和 75,000 $。 每秒产生 +5 影响力。 帮助通过一项法律，要求大学正式承认闲置游戏为官方运动，并为球队球衣和网吧提供训练资金。",
    "Costs 120 Missed Opportunities and $2500. Requires a High-Performance Computer. If you're going to get the whole world to play Existence Simulator, you'll need to live on the cutting edge of science. Take an online class by Professor Dr. Gabriella Timeknifetry, the leading expert in quantum computing manifold structures.": "花费 120 次错过的机会和 2500 $。 需要高性能计算机。 如果你想让全世界都玩《存在模拟器》，你需要生活在科学的前沿。 参加由量子计算流形结构领域的领先专家 Gabriella Timeknifetry 教授教授的在线课程。",
    "Costs 10,000 Knowledge, 10,000 Influence, and $225,000. Generate +5 Influence per second. The world has evolved, and not everyone needs to work all the time. Help pass a law that provides a basic income safety net for people to take care of themselves and their family without forcing them to participate in an exploitative labor system because there's no other way to pay your bills.": "花费 10,000 知识、10,000 影响力和 225,000 $。 每秒产生 +5 影响力。 世界已经发展，并不是每个人都需要一直工作。 帮助通过一项法律，为人们提供基本收入安全网，让他们能够照顾自己和家人，而不会因为没有其他方式支付账单而迫使他们参与剥削性劳动系统。",
    "This is it: your magnum opus. Build the gravity-defying, expectation-satisfying, world-renowned idle clicker game 'Existence Simulator.' Costs 300 Knowledge and 300 Missed Opportunities. Unlocks Worldwide Players. Blog Posts and Podcast Episodes generate 25% more Influence.": "这就是它：你的代表作。 打造反重力、满足期望、世界知名的闲置点击游戏“存在模拟器”。 花费 300 知识和 300 错失机会。 解锁全球玩家。 博客文章和播客剧集产生的影响力增加了 25%。",
    "Generates 75 Missed Opportunities. Significantly reduces anxiety per second for an amount of time based on your tolerance. If Online Learning is unlocked, generates Knowledge per second when you Read. (Once your high is over, you'll be able to re-purchase more cannabis).": "产生 75 个错失的机会。 根据您的耐受性，在一定时间内显着减少每秒的焦虑。 如果在线学习已解锁，阅读时每秒生成知识。 （一旦你的高潮结束，你就可以重新购买更多的大麻）。",
    "Costs 45 Missed Opportunities, $20, and 200 Knowledge. Must have at least a mid-range computer, have learned audio recording, and have purchased recording equipment. Podcasts generate some Money and a lot of Influence with each Podcast Episode.": "花费 45 个错失的机会、20 $和 200 个知识。 必须至少有一台中档电脑，学习过录音，并购买了录音设备。 播客通过每个播客集产生一些金钱和很大的影响力。",
    "Costs 5,000 Knowledge, 5,000 Influence, and $100,000. Generate +5 Influence per second. Help pass the Baby Existence Simulator Trainer (BEST) Law, which provides free, single-button idle games for babies to prepare them to play Existence Simulator.": "花费 5,000 知识、5,000 影响力和 100,000 $。 每秒产生 +5 影响力。 帮助通过婴儿生存模拟器训练师 (BEST) 法，该法为婴儿提供免费的单键放置游戏，让他们为玩生存模拟器做好准备。",
    "Costs 7,000 Knowledge, 7,000 Influence, and $150,000. Generate +5 Influence per second. Many people can't play Existence Simulator all day because they need to make more money to afford childcare, a viscious cycle of of needless expenses that keeps them in poverty. Help Pass a law that provides free childcare for anyone who regularly plays Existence Simulator.": "花费 7,000 知识、7,000 影响力和 150,000 $。 每秒产生 +5 影响力。 许多人不能整天玩生存模拟器，因为他们需要赚更多的钱来支付托儿费用，这是一个让他们陷入贫困的不必要开支的恶性循环。 帮助通过一项为经常玩《存在模拟器》的人提供免费托儿服务的法律。",
    "Costs 6,000 Knowledge, 6,000 Influence, and $125,000. Generate +5 Influence per second. Many people can't play Existence Simulator all day because they need to feed their families. Help pass a law that provides free food rations to anyone who plays Existence Simulator.": "花费 6,000 知识、6,000 影响力和 125,000 $。 每秒产生 +5 影响力。 许多人不能整天玩生存模拟器，因为他们需要养家糊口。 帮助通过一项法律，为任何玩生存模拟器的人提供免费食物配给。",
    "Costs 8,000 Knowledge, 8,000 Influence, and $175,000. Generate +5 Influence per second. Many people can't play Existence Simulator all day because they need to make money so they can afford healthcare, a viscious cycle of of needless expenses that keeps them in poverty. Help pass a law that provides full healthcare reimbursement via pre-approved rebates for citizens playing Existence Simulator.": "花费 8,000 知识、8,000 影响力和 175,000 $。 每秒产生 +5 影响力。 许多人不能整天玩生存模拟器，因为他们需要赚钱才能负担得起医疗保健，这是一个让他们陷入贫困的不必要开支的恶性循环。 帮助通过一项法律，通过预先批准的折扣为玩《存在模拟器》的公民提供全额医疗保健报销。",
    "Costs 50 Missed Opportunities and 200 Knowledge. Must have read about game theory and development. Must know advanced coding. Must have a mid-range computer or better. Anxiety per second reduced by 5. Working makes more money, and you generate more money per second.": "花费 50 错失的机会和 200 知识。 必须阅读博弈论和发展。 必须知道高级编码。 必须有中档电脑或更好的电脑。 每秒焦虑减少 5。工作赚更多钱，你每秒产生更多钱。",
    "Costs 50 Knowledge. Must know HTML and have read book about the business of podcasting. Unlocks ability to hire Freelancers and to build automations. Freelancers convert $25 into one Podcast Episode. Passively generates Money per second based on number of Episodes published.": "花费 50 知识。 必须了解 HTML 并阅读过有关播客业务的书籍。 解锁雇佣自由职业者和构建自动化的能力。 自由职业者将 25 $转换为一集播客。 根据已发布的剧集数，每秒被动地产生金钱。",
    "Costs 9,000 Knowledge, 9,000 Influence, and $200,000. Generate +5 Influence per second. Many people can't play Existence Simulator all day because there's nowhere that offers affordable rent, so they have to work overtime and multiple jobs just to afford basic housing -- a viscious cycle of of needless effort that keeps them in poverty. Help pass a law that provides housing stipends for all citizens playing Existence Simulator.": "花费 9,000 知识、9,000 影响力和 200,000 $。 每秒产生 +5 影响力。 许多人不能整天玩生存模拟器，因为没有地方提供负担得起的租金，所以他们不得不加班和多份工作才能买得起基本的住房——这是一个让他们陷入贫困的无谓努力的恶性循环。 帮助通过一项为所有玩生存模拟器的公民提供住房津贴的法律。",
    "You are immortal.": "你是不朽的。",
    "You're a pro!": "你是专业人士！",
    "Costs 45 Missed Opportunities, $20, and 100 Knowledge. You must know HTML. Blogs generate some Influence and a lot of Money with each Blog Post.": "花费 45 个错失的机会、20 $和 100 个知识。您必须了解 HTML。博客通过每篇博客文章产生一些影响力和大量金钱。",
    "Costs 50 Knowledge. Must have read book about the business of blogging. Each Blog Post passively generates Money.": "花费 50 知识。必须阅读有关博客业务的书。每个博客帖子都会被动地产生金钱。",
    "Costs 50 Knowledge. Must know Javascript and have monetized your blog. Auto-hire 1 Freelancer every second.": "花费 50 知识。必须了解 Javascript 并通过您的博客获利。每秒自动雇用 1 名自由职业者。",
    "Costs 50 Missed Opportunities and 100 Knowledge. Must know HTML and Javascript. Anxiety per second resets to zero. Working makes more money, and you generate more money per second.": "花费 50 个错失的机会和 100 个知识。必须了解 HTML 和 Javascript。每秒的焦虑重置为零。工作赚更多的钱，你每秒产生更多的钱。",
    "Costs 50 Missed Opportunities if you worked hard in school, 100 if you didn't. In addition to slightly higher pay per work, generates some money per second.": "如果您在学校努力学习，则损失 50 个错过的机会，如果您不努力，则损失 100 个。除了每件作品的报酬略高，每秒产生一些钱。",
    "Costs 75 Knowledge. Must know Advanced Coding. Auto-hire up to 2 Freelancer every second.": "花费 75 知识。必须了解高级编码。每秒自动雇佣多达 2 名自由职业者。",
    "Costs 90 Knowledge. Must know Advanced Coding. Auto-hire 1 Freelancer every second. +25% Influence from Podcast Episodes.": "花费 90 知识。必须了解高级编码。每秒自动雇用 1 名自由职业者。 +25% 来自播客剧集的影响。",
    "Costs 90 Missed Opportunities and $69. Must have a Mid-Range Computer or better. Unlocks improved automations. Combined with reading about game development and theory, unlocks getting a gamedev job and writing your own games.": "花费 90 次错过的机会和 69 $。必须有中档电脑或更好的电脑。解锁改进的自动化。结合阅读游戏开发和理论，解锁获得游戏开发工作并编写自己的游戏。",
    "Create clicker game ASMR content": "创建答题器游戏 ASMR 内容",
    "create episode": "创建剧集",
    "create post": "创建帖子",
    "Create Something": "创造一些东西",
    "Develop a version of human consciousness expressed as idle game mechanics": "开发一种表示为空闲游戏机制的人类意识版本",
    "Do Something": "做一点事",
    "doomscroll": "末日卷轴",
    "Existence Simulator ♥ by": "存在模拟器♥",
    "Express Yourself": "表达你自己",
    "for +1 click/second": "+1 点击/秒",
    "for +1/click": "+1/点击",
    "Game Over": "游戏结束",
    "Generate +": "生成 +",
    "generate +1 anxiety": "产生+1焦虑",
    "generate 50 Anxiety.": "产生 50 点焦虑。",
    "generate passive income": "产生被动收入",
    "generate passive influence": "产生被动影响",
    "Get a better job": "找一份更好的工作",
    "Get a Game Developer job": "获得游戏开发人员的工作",
    "Get a Junior Developer Job": "获得初级开发人员工作",
    "Get an entry-level job": "获得入门级工作",
    "Get on TikTok": "上 TikTok",
    "Get on Twitter": "上推特",
    "Get sponsorship from an energy drink company": "从能量饮料公司获得赞助",
    "Get sponsorship from gaming chair company": "从游戏椅公司获得赞助",
    "Get sponsorship from mouse company": "获得鼠标公司的赞助",
    "Good! Now try to get your number up to 100.": "好的！现在尝试将您的号码增加到 100。",
    "Great job! Can you make it to 1,000?": "做得好！你能做到1000吗？",
    "heal the world with games": "用游戏治愈世界",
    "Help pass Food Rations Law": "帮助通过口粮法",
    "Help pass Free Childcare Law": "帮助通过免费托儿法",
    "Help pass Healthcare Rebates Law": "帮助通过医疗回扣法",
    "Help Pass Higher Education Grants for Idle Gamers Law": "帮助通过空闲游戏玩家法的高等教育补助金",
    "Help pass Housing Stipends Law": "帮助通过住房津贴法",
    "Help Pass K-12 Idle Game Curriculum Law": "帮助通过 K-12 空闲游戏课程法",
    "Help Pass T.V. Law": "帮助通过电视法",
    "Help pass the B.E.S.T. Law": "帮助通过 B.E.S.T.法律",
    "Help pass Universal Income Law": "帮助通过全民收入法",
    "hire freelancer": "聘请自由职业者",
    "Hire research firm to study player growth": "聘请研究公司研究玩家成长",
    "Improve automations for blog": "改进博客的自动化",
    "Improve automations for podcast": "改进播客的自动化",
    "Influence": "影响",
    "Knowledge": "知识",
    "Learn Advanced Coding": "学习高级编码",
    "Learn audio recording": "学习录音",
    "Learn how to write HTML": "学习如何编写 HTML",
    "Learn Javascript": "学习 Javascript",
    "Learn Quantum Coding": "学习量子编码",
    "Learn Theoretical Coding": "学习理论编码",
    "Listen to a game theory audio book": "听一本博弈论有声读物",
    "Lose 1 day": "损失 1 天",
    "Missed Opportunities": "错过的机会",
    "Missed Opportunities,": "错失良机，",
    "Monetize blog": "通过博客获利",
    "Monetize podcast": "通过播客获利",
    "Money": "钱",
    "Must be 21+ years old) Costs $50, then you can smoke it. Smoking cannabis immediately generates 75 Missed Opportunities. Reading while high increases the amount of Knowledge you passively generate per second.": "必须是 21 岁以上）成本 50 $，然后你可以吸烟。吸食大麻会立即产生 75 个错失机会。高读时会增加你每秒被动生成的知识量。",
    "Play A Game": "玩个游戏",
    "playing Existence Simulator.": "玩生存模拟器。",
    "read": "读",
    "Read a blogging business book": "阅读博客商业书籍",
    "Read a game development book": "阅读游戏开发书籍",
    "Read a podcasting business book": "阅读播客业务书籍",
    "Refactor automations for blog": "重构博客自动化",
    "Run for President of the World": "竞选世界总统",
    "Smoke some cannabis": "抽一些大麻",
    "Spend": "花费",
    "Spend Your Money": "花你的钱",
    "Start a Blog about idle clicker games": "建立一个关于放置点击游戏的博客",
    "Start a Podcast about idle clicker games": "开始播客关于闲置答题器游戏",
    "Stream on Twitch": "在 Twitch 上直播",
    "Stream on YouTube": "在 YouTube 上流式传输",
    "There": "那里",
    "to this →": "到这里 →",
    "Total clicks ever": "总点击次数",
    "Try Your Best": "尽你所能",
    "turn off": "关",
    "Worldwide Players": "全球玩家",
    "Write a multiplayer game": "编写多人游戏",
    "Write a single-player game": "编写单人游戏",
    "Write an idle clicker game": "编写一个空闲的点击游戏",
    "> As you exist, you generate anxiety. Try generating at least 10.": "> 当你存在时，你会产生焦虑。尝试生成至少 10 个。",
    "> The anxiety just builds and builds -- just like real life! You can always reduce your anxiety immediately by Crying. Try that now.": "> 焦虑不断增加——就像现实生活一样！你总是可以通过哭泣立即减轻你的焦虑。现在试试。",
    "> Welcome to the Existence Simulator. Begin existing by clicking the 'Exist' button.": "> 欢迎来到存在模拟器。通过单击“存在”按钮开始存在。",
    "Add": "添加",
    "Adds a small amount of anxiety": "增加少量焦虑",
    "Anxiety": "焦虑",
    "anxiety now,": "现在的焦虑，",
    "Anxiety Reduction from Games": "从游戏中减少焦虑",
    "are 250.00  people": "是 250.00 人",
    "Auto Clickers": "自动答题器",
    "Automations are": "自动化是",
    "Build automations for blog": "为博客构建自动化",
    "Build automations for podcast": "为播客构建自动化",
    "but also generate +0.31 Anxiety per second.": "但也会每秒产生 +0.31 焦虑。",
    "Buy a cheap computer": "买一台便宜的电脑",
    "Buy a coffee maker": "买个咖啡机",
    "Buy a good WiFi router": "买一个好的WiFi路由器",
    "Buy a high-performance computer": "购买高性能计算机",
    "Buy a mid-range computer": "买一台中档电脑",
    "Buy a plant": "购买植物",
    "Buy a scented candle": "买一支香薰蜡烛",
    "Buy a weighted blanket": "买一条加重毛毯",
    "Buy an idle clicker game": "购买一个空闲的点击游戏",
    "Buy audio recording equipment": "购买录音设备",
    "Buy pro audio equipment": "购买专业音频设备",
    "Buy some cannabis": "买一些大麻",
    "Buy some comfy pants": "买一条舒服的裤子",
    "Click at least three times.": "点击至少三下。",
    "clicks/second": "点击/秒",
    "Convert $25 into 1 Blog Post.": "将 25 $转换为 1 篇博文。",
    "Convert $45 into 1 Podcast Episode.": "将 45 $转换为 1 集播客。",
    "Convert 1 Missed Opportunity into 1 Blog Post.": "将 1 个错过的机会转换为 1 个博客文章。",
    "Convert 1 Missed Opportunity into some Knowledge": "将 1 个错失的机会转化为一些知识",
    "Convert 1 Missed Opportunity into some Money": "将 1 个错失的机会转化为金钱",
    "Convert 3 Missed Opportunities into 1 Podcast Episode.": "将 3 个错过的机会转换为 1 个播客集。",
    "Costs $1,099. Unlocks ability to learn Advanced Coding, and is one of the prerequisites to Podcasting and writing your own games.": "售价 1,099 $。解锁学习高级编码的能力，并且是播客和编写自己的游戏的先决条件之一。",
    "Costs $129. A good microphone, a mixer, some headphones, and some software for session recording. One of the prerequisites to starting a Podcast.": "售价 129 $。一个好的麦克风、一个混音器、一些耳机和一些用于会话录制的软件。开始播客的先决条件之一。",
    "Costs $1499. Doubles the Influence generated by your Podcast Episodes.": "售价 1499 $。将您的播客剧集产生的影响力加倍。",
    "Costs $19.99. Reduces Anxiety per second by 1, and cancels any current effects that are increasing your anxiety.": "售价 19.99 $。每秒减少 1 点焦虑，并取消当前任何增加焦虑的效果。",
    "Costs $19.99. Working no longer increases anxiety. If you have a better job, make slightly more money per second.": "售价 19.99 $。工作不再增加焦虑。如果你有一份更好的工作，每秒赚的钱稍微多一点。",
    "Costs $219. Connects you to the Information Superhighway. Prerequisite to unlocking Online Learning (learn new skills to make Money and eventually generate Influence). Don't forget to buy a good Wi-Fi router, too!": "售价 219 $。将您连接到信息高速公路。解锁在线学习的先决条件（学习新技能以赚钱并最终产生影响力）。也别忘了买一个好的 Wi-Fi 路由器！",
    "Costs $29. Play this indie game to reduce your anxiety.": "费用为 29 $。玩这个独立游戏来减少你的焦虑。",
    "Costs $29.99. Reduces Anxiety per second by 2, and cancels any current effects that are increasing your anxiety.": "售价 29.99 $。每秒减少 2 点焦虑，并取消当前任何增加焦虑的效果。",
    "Costs $3,999. Unlocks learning Quantum Coding.": "售价 3,999 $。解锁学习量子编码。",
    "Costs $39.99. Reduces Anxiety per second by 3, and cancels any current effects that are increasing your anxiety.": "售价 39.99 $。每秒减少 3 点焦虑，并取消当前任何增加焦虑的效果。",
    "Costs $419,000. Increases your maximum anxiety to 100,000.": "花费 419,000 $。将您的最大焦虑增加到 100,000。",
    "Costs $49. Along with buying a computer, unlocks Online Learning, where you Read to convert Missed Opportunities into Knowledge.": "费用为 49 $。除了购买电脑，还可以解锁在线学习，您可以通过阅读将错失的机会转化为知识。",
    "Costs $49.99 and 40 Knowledge. After reading this and listening to the game theory audio book, you'll be able to start making your own games.": "花费 49.99 $和 40 知识。阅读完本文并听完博弈论有声读物后，您就可以开始制作自己的游戏了。",
    "Costs $49.99 and 65 Knowledge. Prerequisite to writing your own games.": "花费 49.99 $和 65 知识。编写自己的游戏的先决条件。",
    "Costs $49.99 and 75 Knowledge. Unlocks monetizing, automating, and hiring freelancers for your blog.": "花费 49.99 $和 75 知识。为您的博客解锁货币化、自动化和雇佣自由职业者。",
    "Costs $49.99. Reduces anxiety per second by 4, and cancels any current effects that are increasing your anxiety.": "售价 49.99 $。每秒减少 4 点焦虑，并取消当前增加焦虑的任何效果。",
    "Costs $50,000. A team of experts will study the worldwide playerbase of Existence Simulator to develop a set of recommendations for generating player growth.": "费用为 50,000 $。一个专家团队将研究 Existence Simulator 的全球玩家群，以制定一套促进玩家成长的建议。",
    "Costs $59.99 and 85 Knowledge. Shows you everything you need to start a Podcast. Podcasts generate some Money and a lot of Influence.": "花费 59.99 $和 85 知识。向您展示开始播客所需的一切。播客产生了一些金钱和很大的影响力。",
    "Costs 10 Missed Opportunities. Generates +1 Missed Opportunities per second and also slightly increases Anxiety per second (though we never really know by how much, do we?).": "损失 10 个错失的机会。每秒产生 +1 错失机会，并且每秒略微增加焦虑（尽管我们永远不知道增加了多少，对吗？）。",
    "Costs 10 missed opportunities. Slightly increases Missed Opportunities per second. Maybe helps with anxiety, too?": "损失 10 个错失的机会。略微增加每秒错过的机会。也许也有助于缓解焦虑？",
    "Costs 100 Knowledge and 100 Missed Opportunities. Must have read about game theory and about game development. Podcast Episodes and Blog Posts generate 25% more Money and Influence.": "花费 100 知识和 100 错失机会。必须阅读博弈论和博弈开发。播客集和博客文章产生的金钱和影响力增加了 25%。",
    "Costs 100 Knowledge. Requires mid-range computer or better. Auto-hire up to 3 Freelancer every second. If you've written a game, Blog Posts now generate some Influence.": "花费 100 知识。需要中档电脑或更好的电脑。每秒自动雇佣多达 3 名自由职业者。如果您编写了游戏，博客文章现在会产生一些影响力。",
    "Costs 1000 Knowledge, 500 Missed Opportunities, and $129. Generates 3 Anxiety per second in exchange for 1 Influence per second.": "花费 1000 知识、500 错失机会和 129 $。每秒产生 3 点焦虑以换取每秒 1 点影响。",
    "Costs 1000 Knowledge. Must have at least 100 Influence. Generate +1 Influence per second and $15,000.": "花费 1000 知识。必须至少有 100 影响力。每秒产生 +1 影响力和 15,000 $。",
    "Costs 120 Knowledge. Auto-hire up to 2 Freelancer every second. +25% Influence from Podcast Episodes.": "花费 120 知识。每秒自动雇佣多达 2 名自由职业者。 +25% 来自播客剧集的影响。",
    "Costs 150 Knowledge. Must know Advanced Coding. Auto-hire up to 3 Freelancer every second. +25% Influence from Podcast Episodes.": "花费 150 知识。必须了解高级编码。每秒自动雇佣多达 3 名自由职业者。 +25% 来自播客剧集的影响。",
    "Costs 1500 Knowledge, 750 Missed Opportunities, and $129. Generates 3 Anxiety per second in exchange for 1 Influence per second.": "花费 1500 知识、750 错失机会和 129 $。每秒产生 3 点焦虑以换取每秒 1 点影响。",
    "Costs 1500 Knowledge. Must have at least 550 Influence. Generate +1 Influence per second and $17,500.": "花费 1500 知识。必须至少有 550 影响力。每秒产生 +1 影响力和 17,500 $。",
    "Costs 2,500 Knowledge, 1,750 Influence, and $25,000. Generate +5 Influence per second. Help pass a law that livestreams Existence Simulator games all hours of the day and night.": "花费 2,500 知识、1,750 影响力和 25,000 $。每秒产生 +5 影响力。帮助通过一项法律，在白天和黑夜的所有时间里直播 Existence Simulator 游戏。",
    "Costs 20 Missed Opportunities and $29. Unlocks starting a Blog. Prerequisite to learning more advanced programming.": "花费 20 个错过的机会和 29 $。解锁开始博客。学习更高级编程的先决条件。",
    "Costs 20 Missed Opportunities. Makes it easier to find a job, but also increases the anxiety you generate passively. Maybe improves life later on, too?": "损失 20 个错失的机会。让找工作更容易，但也会增加你被动产生的焦虑。也许以后也会改善生活？",
    "Costs 20,000 Knowledge, 20,000 Influence, and $250,000. +100 Influence per second. Slowly but surely, everyone on Earth will play Existence Simulator.": "花费 20,000 知识、20,000 影响力和 250,000 $。 +100 影响每秒。慢慢但肯定地，地球上的每个人都会玩《存在模拟器》。",
    "Costs 200 Knowledge and 200 Missed Opportunities. Blog Posts and Podcast Episodes generate 25% more Influence. Prerequisite to writing 'Existence Simulator,' an idle clicker game that will take over the world.": "花费 200 知识和 200 错失机会。博客文章和播客剧集产生的影响力增加了 25%。编写“生存模拟器”的先决条件，这是一款将接管世界的闲置点击游戏。",
    "Costs 2000 Knowledge. Must have at least 1,750 Influence. Generate +1 Influence per second and $45,000.": "花费 2000 知识。必须至少有 1,750 影响力。每秒产生 +1 影响力和 45,000 $。",
    "Costs 25 Missed Opportunities if you worked hard in school, 50 if you didn't. Unlocks the ability to convert Missed Opportunities into money by Working--just like real life!": "如果您在学校努力学习，则损失 25 个错过的机会，如果您不努力，则损失 50 个。解锁通过工作将错过的机会转化为金钱的能力——就像现实生活一样！",
    "Costs 25 Missed Opportunities. Unlocks Doomscrolling (hit spacebar to instantly generate 50 Anxiety and 5 Missed Opportunities).": "损失 25 个错失的机会。解锁末日滚动（按空格键立即产生 50 焦虑和 5 错失机会）。",
    "Costs 2500 Knowledge. Must have a Podcast with at least 100 episodes published. Must have at least 2,500 Influence. Generate +1 Influence per second and $80,000.": "花费 2500 知识。播客必须至少发布 100 集。必须至少有 2,500 影响力。每秒产生 +1 影响力和 80,000 $。",
    "Costs 3,000 Knowledge, 3,000 Influence, and $50,000. Generate +5 Influence per second. Help pass a law that requires K-12 public schools to teach idle games every year.": "花费 3,000 知识、3,000 影响力和 50,000 $。每秒产生 +5 影响力。帮助通过一项要求 K-12 公立学校每年教授闲置游戏的法律。",
    "Costs 30 Missed Opportunities and $29. What is siblance? How do you cut the low-end and still sound good? Everyone should know how to record good audio. One of the prerequisites to starting a Podcast.": "花费 30 次错过的机会和 29 $。什么是消音？你如何削减低端并且仍然听起来不错？每个人都应该知道如何录制好的音频。开始播客的先决条件之一。",
    "Costs 40 Missed Opportunities and $29. Unlocks building automations for your Blog and/or Podcast.": "花费 40 次错过的机会和 29 $。为您的博客和/或播客解锁楼宇自动化。",
    "Costs 400 Missed Opportunities and $25,000. If your theories are correct, this will allow your consciousness to live on forever in a distributed, world-wide network of 'Existence Simulator' games.": "花费 400 次错过的机会和 25,000 $。如果你的理论是正确的，这将使你的意识永远存在于分布式的、全球范围内的“存在模拟器”游戏网络中。",
    "'The Fourth Wall', an Idle Clicker Game": "“第四面墙”，一款放置点击游戏",
    "✍🏽 Blogging": "✍🏽 写博客",
    "🎙️ Podcasting": "🎙️ 播客",
    "🎮 Game Development": "🎮 游戏开发",
    "> Almost done! Let's have one more good Cry.": "> 快完成了！ 让我们再多哭几次。",
    "> Crying helps reduce anxiety immediately--but it also increases the amount of anxiety you passively generate. Try Crying five times.": "> 哭泣有助于立即减少焦虑——但它也会增加你被动产生的焦虑程度。 尝试哭五次。",
    "> Now you're a regular anxiety machine--just like real life! Try making it to 100 anxiety.": "> 现在你是一个经常焦虑的机器——就像现实生活一样！ 尝试达到 100 焦虑。",
    "> Each time you cry, you also generate Missed Opportunities. One of the key features of existing is trading your Missed Opportunties for different ways to Try your Best. Life's also supposed to be fun! So don't forget to Express Yourself, too.": "> 每次你哭泣，你也会产生错失的机会。 现有的主要功能之一是将您错过的机会换成不同的方式来尽力而为。 生活也应该是有趣的！ 所以也不要忘记表达自己。",
    "> 😵‍💫 Now you know that mitochondria are the powerhouse of the cell. Your social anxiety is through the roof, but maybe now you can find yourself a job!": "> 😵‍💫 现在您知道线粒体是细胞的动力源。 您的社交焦虑已达到顶峰，但也许现在您可以找到一份工作！",
    "> You've unlocked Working! When you Work, you convert Missed Opportunities into some Money. You can use your money to buy things to help reduce your Anxiety -- or create new avenues of Money generation!": "> 你已经解锁了工作！ 当你工作时，你将错过的机会转化为一些金钱。 你可以用你的钱买东西来帮助减少你的焦虑——或者创造新的赚钱途径！",
    "> The job hunt begins!": "> 求职开始了！",
    "> Look at you taking charge of your life, making your own money, and not letting things get the best of you! Why not spend some of that hard-earned money? Go on! You've earned it!": "> 看看你掌控自己的生活，自己赚钱，而不是让事情占上风！ 为什么不花一些来之不易的钱呢？ 继续！ 这是你应得的！",
    "Applying to places in town...": "申请市区...",
    "Asking around for openings...": "到处问开口...",
    "Checking online for job openings...": "正在网上查询职位空缺...",
    "Completing a background check...": "完成背景调查...",
    "Filling out paperwork...": "填写文书...",
    "Interviewing over video chat...": "视频聊天面试...",
    "Interviewing with a place that seems nice...": "面试一个看起来不错的地方...",
    "Interviewing with another place that seems okay...": "面试另一个看起来还不错的地方...",
    "Reading training binder...": "阅读培训活页夹...",
    "Signing documents...": "签署文件...",
    "Still waiting for a call-back...": "还在等回电...",
    "Studying algebra...": "学习代数...",
    "Studying calculus...": "学习微积分...",
    "Studying civics...": "学习公民...",
    "Studying computers...": "学电脑...",
    "Studying english...": "学习英语...",
    "Studying finance...": "学金融...",
    "Studying game development (elective)...": "学习游戏开发（选修）...",
    "Studying history...": "学习历史...",
    "Studying literature...": "学习文学...",
    "Studying psychology...": "学心理学...",
    "You have unlocked Working, which converts Missed Opportunity into Money (and anxiety, too, if you don't drink Coffee).": "你已经解锁了工作，它将错失的机会转化为金钱（如果你不喝咖啡，也会感到焦虑）。",
    "You traded a social life for trying to actually learn something in school. But what did you learn, really?": "你放弃了社交生活，试图在学校真正学习一些东西。 但是你真的学到了什么？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)  episodes$/, '$1  情节'],
	[/^([\d\.]+)  posts$/, '$1  帖子'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) missed opportunities$/, '$1 错过的机会'],
    [/^([\d\.]+) anxiety$/, '$1 焦虑'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);