/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "anxiety": "焦虑",
    "anxiety now, but generate +1 anxiety": " 焦虑现在，但产生 +1 焦虑",
    "Anxiety per second": "焦虑每秒",
    "Buy a house": "买房子",
    "Buy an NFT": "购买 NFT",
    "Costs $1,000.": "费用为 1,000 美元。",
    "Costs $200 in collateral. +$200.": "抵押品费用为 200 美元。 +200 美元。",
    "Costs $50,000 and 4,500 missed opportunities. +$1/s.": "花费 50,000 美元和 4,500 次错失机会。 + 1 美元/秒。",
    "Costs $550,000. -500 anxiety/s.": "花费 550,000 美元。 -500 焦虑/秒。",
    "Costs 10 missed opportunities & must work hard in school. Unlocks the ability to work for money.": "损失 10 次错过的机会，并且必须在学校努力学习。解锁为钱工作的能力。",
    "Costs 3 missed opportunities. Maybe helps with anxiety?": "损失 3 次错失机会。也许有助于缓解焦虑？",
    "Costs 60 missed opportunities and": "损失 60 次错失机会和",
    "Costs 990 anxiety and 5,500 missed opportunities. +$1/s.": "花费 990 次焦虑和 5,500 次错失机会。 + 1 美元/秒。",
    "cry": "哭",
    "days old.": " 天了。",
    "doubt": "怀疑",
    "exist": "存在",
    "Existence Simulator": "存在模拟器",
    "Forget hobbies! Study hard for those tests and make something of yourself. (": "忘记爱好！为这些测试努力学习，让自己有所作为。 (",
    "Free! Permanently increases anxiety per second and missed opportunities per second. But by how much? (We never really know, do we?": "自由！每秒永久增加焦虑和每秒错失的机会。但是多少呢？ （我们从来都不知道，不是吗？",
    "Generate money (you have $": "赚钱（你有 $",
    "generating": "生成",
    "Get a good job": "找个好工作",
    "Get a social media account": "获取社交媒体帐户",
    "Go to college": "去上大学",
    "LOADING...": "正在加载...",
    "Look for a job": "找工作",
    "Lose": "失去",
    "missed opportunities": "错失良机",
    "Missed opportunities per second": "每秒错失的机会",
    "Must use BEFORE 18th birthday": "必须在 18 岁生日之前使用",
    "Okay": "好的",
    "only $5.99": "只需 5.99 美元",
    "Panic Attack": "惊恐发作",
    "QQ群号": "QQ群号",
    "Start taking naps": "开始小睡",
    "Take an online class": "参加在线课程",
    "Take out a loan": "拿出贷款",
    "Thanks": "谢谢",
    "This game is meant to be played on desktop devices. Sorry.": "该游戏旨在在桌面设备上玩。对不起。",
    "try your best": "尽你所能",
    "Welcome to the Existence Simulator. Begin existing by clicking the 'Exist' button.": "欢迎来到存在模拟器。通过单击“存在”按钮开始存在。",
    "work": "工作",
    "Work hard in school": "在学校努力工作",
    "x": "X",
    "years and": " 年",
    "years old.": "岁。",
    "You are": "你活了 ",
    "You had a nervous breakdown at": "你精神崩溃了，在",
    "You no longer exist.": "你已经不存在了。",
    "As you exist, you generate anxiety. Try generating at least 10.": "当你存在时，你会产生焦虑。 尝试生成至少 10 个。",
    "Crying removes anxiety immediately--and increases the amount of anxiety you passively generate. Try generating 5 anxiety per second by Crying more.": "哭泣会立即消除焦虑——并增加你被动产生的焦虑程度。 尝试通过多哭，达到每秒产生 5 焦虑。",
    "Generating anxiety by just existing takes a lot of effort. To generate anxiety automatically, try Crying.": "仅仅通过存在来产生焦虑需要付出很多努力。 要自动产生焦虑，请尝试哭泣。",
    "Now you're a regular anxiety machine--just like real life! Try making it to 200 anxiety.": "现在你是一个经常焦虑的机器——就像现实生活一样！ 尝试达到 200 焦虑。",
    "The more you exist, the more anxiety you generate. If you max out your anxiety, you'll have a nervous breakdown (game over), so you'll need to use it on something. The 'Doubt' button generates Missed Opportunities that you can exchange for anxiety.": "你存在的越多，你产生的焦虑就越多。 如果你最大限度地消除焦虑，你就会精神崩溃（游戏结束），所以你需要在某些事情上使用它。 “怀疑”按钮会产生错失的机会，您可以用这些机会换取焦虑。",
    "Now you know the mitochondria are the powerhouse of the cell. Your social anxiety is through the roof, but maybe now you can find yourself a job!": "现在你知道线粒体是细胞的动力源。 您的社交焦虑已达到顶峰，但也许现在您可以找到一份工作！",
    "Now you're a regular anxiety machine--just like real life! Try making it to 200 anxiety.": "现在你是一个经常焦虑的机器——就像现实生活一样！ 尝试达到 200 焦虑。",
    "Thanks to all the new skills you've earned, one day you might be able to earn more money at a job you may potentially find in the future when jobs for that skillset are more available!": "多亏了你获得的所有新技能，有一天你可能会在一份工作中赚到更多的钱，当该技能组的工作更多可用时，你可能会找到一份工作！",
    "The only companies hiring right now are the ones paying the bare minimum. But hey -- at least you have your health! (for now!": "目前唯一招聘的公司是支付最低工资的公司。 但是，嘿 - 至少你有你的健康！ （目前！",
    "You're trying to sleep more, which is generating missed opportunities--but its getting harder to fall asleep, so you're generating more anxiety, too.": "你试图睡得更多，这会产生错失的机会——但它越来越难以入睡，所以你也会产生更多的焦虑。",
    "Your social anxiety goes down a bit, but now that you're doomscrolling everyday it's even harder to fall asleep and focus on things that matter (which is what again?": "你的社交焦虑稍微下降了一点，但现在你每天都在做末日卷轴，所以更难入睡并专注于重要的事情（这又是什么？",
    "Now you are really \"enjoying\" what life has to offer. Oh, what beauty it is to be human! Spend your missed opportunties by Trying your Best.": "现在你真的“享受”了生活所提供的一切。 哦，做人是多么美好啊！ 尽最大努力度过错过的机会。",
    "(thanks to your friend's referral code). Maybe you can earn more money?": "（感谢您朋友的推荐代码）。 也许你可以赚更多的钱？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) missed opportunities$/, '$1 错过的机会'],
    [/^([\d\.]+) anxiety$/, '$1 焦虑'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);